### ISSUE TITLE
Summary results page bit busy

### ISSUE THREAD

**Issue by amberfoam** [fo-am/viruscraft2#71]
Could we reduce the text and numbers a bit? Not sure how's best, head is in mongoose-land.

![Screenshot from 2021-06-04 14-12-47](https://user-images.githubusercontent.com/16224139/120806661-086e7400-c53f-11eb-8cca-ad222a41410e.png)

**Comment by nebogeo** [comment]
It doesn't need any of the first info does it really as you were just playing - it only needs your rank
